### ISSUE TITLE
Liquid-Spec - Milestone 1

### ISSUE THREAD

**Issue by DerekStride** [Shopify/liquid-spec#1]
## Goals for Milestone 1

- [x] Improve test organization
- [x] Add the test name to the spec so developers can link the source back to the test in [Shopify/liquid](https://github.com/Shopify/liquid).
- [x] Convert the `environment.json` to YAML
- [x] Run specs in the [Shopify/liquid-wasm](https://github.com/Shopify/liquid-wasm) CI

## Summary

This is the full list of improvements from my handoff conversation with @ggmichaelgo 

- [x] Run specs in the [Shopify/liquid-wasm](https://github.com/Shopify/liquid-wasm) CI
- [x] Convert the `environment.json` to YAML
  - Newlines are not as friendly in JSON
- [ ] Try using ERB to support drops via a `DropFactory`.
- [x] Add the test name to the spec so developers can link the source back to the test in [Shopify/liquid](https://github.com/Shopify/liquid).
- [x] Improve test organization
  - 1 Folder per test is too verbose
  - 1 file for all tests is too condense
  - Try 1 folder per source (e.g. 1 folder for [Shopify/liquid](https://github.com/Shopify/liquid) and 1 for [Shopify/storefront-renderer](https://github.com/Shopify/storefront-renderer)).
  - Have a folder for custom specs that we can easily add to by hand.
- [ ] Spec generator doesn't grab tests that raise a `Liquid::Error` (e.g. `{{ 4 | divided_by: 0 }}`)
  - Improve generator to accept these tests, or
  - These can be ignored and implemented in the custom folder

## Bonus

These are some idea's I've had about usability, some might take a longer time to implement. I'll time box any exploration.

- [x] Vendor the [liquid-spec-generator](https://github.com/Shopify/liquid-spec-generator) inside this repo.
- [x] Invoke generator via a rake task
  - `bundle exec rake generate_spec:liquid`
  - `bundle exec rake generate_spec:storefront_renderer`
  - `bundle exec rake generate_spec:all`
- [x] Do some sorting on generated specs so the diffs from new specs are not random.
